[package]
name = "template-app"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "template-app"
test = false
bench = false

[dependencies]
embassy-executor = { git = "https://github.com/embassy-rs/embassy.git", features = ["arch-cortex-m", "executor-thread"] }
embassy-nrf = { git = "https://github.com/embassy-rs/embassy.git", features = ["nrf52840", "time-driver-rtc1", "gpiote", "time", "unstable-pac"] }
embassy-time = { git = "https://github.com/embassy-rs/embassy.git", features = ["defmt-timestamp-uptime-tms"] }
embassy-futures = { git = "https://github.com/embassy-rs/embassy.git" }

cortex-m-rt = "0.7.5"
cortex-m = { version = "0.7.7", features = ["inline-asm", "critical-section-single-core"] }
defmt-rtt = "1"
panic-probe = { version = "1", features = ["print-defmt"] }
defmt = "1"

[build-dependencies]
memory-spec = "0.1.0"

[profile.release]
debug = 2
lto = "fat"
opt-level = "z"
codegen-units = 1
