[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip nRF52840_xxAA"

[build]
target = "thumbv7em-none-eabihf"
rustflags = [
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=-Tdefmt.x",
    # This is needed if your flash or ram addresses are not aligned to 0x10000 in memory.x
    # See https://github.com/rust-embedded/cortex-m-quickstart/pull/95
    "-C", "link-arg=--nmagic",
    "-C", "link-arg=--print-memory-usage",
]

[env]
DEFMT_LOG = "info"
# Uncomment to see the output of --print-memory-usage
# RUSTC_LOG = "rustc_codegen_ssa::back::link=info"
