[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "nrfdfu"

[build]
target = "thumbv7em-none-eabihf"
rustflags = [
    "-C", "target-cpu=cortex-m4",
    "-W", "linker-messages",
]

[env]
DEFMT_LOG = "info"
