[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip nRF5340_xxAA"

[build]
target = "thumbv8m.main-none-eabihf"
rustflags = [
    "-C", "target-cpu=cortex-m33",
    "-W", "linker-messages",
]
target-dir = "../build/target-app"

[env]
DEFMT_LOG = "info"
